Feature/transformation builder
cloudinary/cloudinary_dart pull request #10
Opened 2022-09-28 13:37 UTC by adimiz1

Add basic transformation builder with support for 
1. Quality
2. Format

2022-09-29 06:38 UTC, strausr reviewed
Do we want to add docstrings now?

2022-10-12 12:02 UTC, const-cloudinary requested changes
Please see the comments

2022-10-12 12:02 UTC, const-cloudinary commented on test/transformation/delivery_test.dart
> +                  .setLossy()
Do we really need `set` prefix for all of these methods?

2022-10-12 12:02 UTC, const-cloudinary commented on lib/src/transformation/delivery/delivery_actions.dart
> +    var anyFormatStr = anyFormat ? "fl_any_format$paramSeparator" : "";
It can be OK for now, I would refactor this code in the future and add `fl_any_format` as a separate flag qualifier.

2022-10-12 12:05 UTC, adimiz1 commented on test/transformation/delivery_test.dart
> +                  .setLossy()
Same as before, since the function and variable cant have the same name I added the set
Thinking about it again it might be a good idea to change the variable name and not the function

2022-10-12 12:06 UTC, adimiz1 commented on lib/src/transformation/delivery/delivery_actions.dart
> +    var anyFormatStr = anyFormat ? "fl_any_format$paramSeparator" : "";
Will do

2022-10-12 20:58 UTC, const-cloudinary approved these changes

2022-10-13 04:43 UTC, merged