Add metadata management context
cloudinary/cloudinary_dart pull request #107
Opened 2024-08-28 10:42 UTC by adimiz1

### Brief Summary of Changes
Add metadata management context

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [ ] Bug fix
- [x] Adds more tests

#### Are tests included?
- [x] Yes
- [ ] No

#### Reviewer, please note:

#### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2024-08-28 12:23 UTC, const-cloudinary requested changes

2024-08-28 12:23 UTC, const-cloudinary commented on api/lib/uploader/uploader.dart
> +    return _uploaderUtils.callApi(request, 'destroy', options: SharedParams());
what is `destroy`? and why all methods below have it?

2024-08-28 12:23 UTC, const-cloudinary commented on api/lib/src/request/model/uploader_params.dart
> -        _cldEncodeSingleContextItem((map.value as String));
What happened to this function: `_cldEncodeSingleContextItem` is it still in use elsewhere?

2024-08-28 12:23 UTC, const-cloudinary commented on api/lib/src/request/model/uploader_params.dart
> +class ContextParams extends UploaderParams {
Do we need to extend `UploaderParams`? looks like most of them are irrelevant for this operation.

2024-08-29 06:13 UTC, adimiz1 commented on api/lib/src/request/model/uploader_params.dart
> +class ContextParams extends UploaderParams {
Fixed to take the layer above that

2024-09-09 10:43 UTC, const-cloudinary approved these changes

2024-09-09 11:04 UTC, merged